# Use the Zephyr Build Docker image as the base
FROM zephyrprojectrtos/zephyr-build:v0.28.5

# Set environment variables
ENV ZEPHYR_TOOLCHAIN_VARIANT=zephyr

# Initialize west and update the modules in /west
WORKDIR /west
RUN west init && west update && cd /west/tools/net-tools && make

ENV ZEPHYR_BASE=/west/zephyr