services:
  devcontainer:
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true
    devices:
      - /dev/net/tun
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:leshan
    command: sleep infinity

  leshan:
    build:
      context: ../leshan
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"